rewrites:
  - from: "Value.Value"
    to: "Value"


  - from: "Validators.AccountSim.ScriptContext"
    to: "ScriptContext"
  - from: "Validators.AccountSim.ScriptContext.inputVal"
    to: "inputVal"
  - from: "Validators.AccountSim.ScriptContext.outputVal"
    to: "outputVal"
  - from: "Validators.AccountSim.ScriptContext.outputDatum"
    to: "outputDatum"
  - from: "Validators.AccountSim.ScriptContext.payments"
    to: "payments"
  - from: "Validators.AccountSim.ScriptContext.signature"
    to: "signature"
  - from: "Validators.AccountSim.ScriptContext.continues"
    to: "continues"
  - from: "Validators.AccountSim.ScriptContext.mint"
    to: "mint"
  - from: "Validators.AccountSim.ScriptContext.inputRef"
    to: "inputRef"
  - from: "Validators.AccountSim.ScriptContext.tokAssetClass"
    to: "tokAssetClass"
  - from: "Validators.AccountSim.ScriptContext.tokenIn"
    to: "tokenIn"
  - from: "Validators.AccountSim.ScriptContext.tokenOut"
    to: "tokenOut"
  - from: "Validators.AccountSim.ScriptContext.time"
    to: "time"
  - from: "Value.emptyValue"
    to: "emptyValue"
  - from: "Value.geq"
    to: "geq"
  - from: "Value.gt"
    to: "gt"
  - from: "Value.leq"
    to: "leq"
  - from: "Value.le"
    to: "le"
  - from: "Validators.AccountSim.newDatum"
    to: "newDatum"
  - from: "Validators.AccountSim.oldValue"
    to: "oldValue"
  - from: "Validators.AccountSim.newValue"
    to: "newValue"
  - from: "Validators.AccountSim.continuing"
    to: "continuing"
  - from: "Validators.AccountSim.getPayments"
    to: "getPayments"
  - from: "Validators.AccountSim.getPayment"
    to: "getPayments"
  - from: "Validators.AccountSim.getMintedAmount"
    to: "getMintedAmount"
  - from: "Validators.AccountSim.ownAssetClass"
    to: "ownAssetClass"
  - from: "Validators.AccountSim.checkTokenIn"
    to: "checkTokenIn"
  - from: "Validators.AccountSim.checkTokenOut"
    to: "checkTokenOut"
  - from: "Validators.AccountSim.checkSigned"
    to: "checkSigned"
  - from: "Validators.AccountSim.checkSigned"
    to: "checkSigned"
  - from: "Validators.AccountSim.iRef"
    to: "iRef"
  - from: "Validators.AccountSim.checkTokenBurned"
    to: "checkTokenBurned"
  - from: "Validators.AccountSim.consumes"
    to: "consumes"
  - from: "Validators.AccountSim.continuingAddr"
    to: "continuingAddr"
  - from: "Validators.AccountSim.checkPayment"
    to: "checkPayment"
  - from: "Validators.AccountSim.now"
    to: "now"
    
  - from: "Validators.AccountSim.ScriptContext.time"
    to: "time"
    
    
    