rewrites:
  - from: "Value.Value"
    to: "Value"
  - from: "Value.emptyValue"
    to: "emptyValue"
  - from: "Value.minValue"
    to: "minValue"
  - from: "Value.geq"
    to: "geq"
  - from: "Value.gt"
    to: "gt"
  - from: "Value.leq"
    to: "leq"
  - from: "Value.le"
    to: "le"
  - from: "Value.assetClassValueOf"
    to: "assetClassValueOf"
  - from: "Value.assetClassValue"
    to: "assetClassValue"
  - from: "Value.assetClassValue"
    to: "assetClassValue"
  - from: "Value.checkMinValue"
    to: "checkMinValue"
  - from: "Value.lovelaces"
    to: "lovelaces"
  - from: "Value.2xMinValue"
    to: "2xMinValue"
    
  - from: "Lib.CurrencySymbol"
    to: "CurrencySymbol"    
  - from: "Lib.TokenName"
    to: "TokenName"    
  - from: "Lib.PubKeyHash"
    to: "PubKeyHash"    
  - from: "Lib.AssetClass"
    to: "AssetClass"    
  - from: "Lib.Address"
    to: "Address"    
  - from: "Lib.TxOutRef"
    to: "TxOutRef"    
  - from: "Lib.Rational"
    to: "Rational"
  - from: "Lib.numerator"
    to: "numerator"
  - from: "Lib.denominator"
    to: "denominator"

  - from: "Validators.AccountSim.ScriptContext"
    to: "ScriptContext"
  - from: "Validators.AccountSim.ScriptContext.inputVal"
    to: "inputVal"
  - from: "Validators.AccountSim.ScriptContext.outputVal"
    to: "outputVal"
  - from: "Validators.AccountSim.ScriptContext.outputDatum"
    to: "outputDatum"
  - from: "Validators.AccountSim.ScriptContext.payments"
    to: "payments"
  - from: "Validators.AccountSim.ScriptContext.signature"
    to: "signature"
  - from: "Validators.AccountSim.ScriptContext.continues"
    to: "continues"
  - from: "Validators.AccountSim.ScriptContext.mint"
    to: "mint"
  - from: "Validators.AccountSim.ScriptContext.inputRef"
    to: "inputRef"
  - from: "Validators.AccountSim.ScriptContext.tokAssetClass"
    to: "tokAssetClass"
  - from: "Validators.AccountSim.ScriptContext.tokenIn"
    to: "tokenIn"
  - from: "Validators.AccountSim.ScriptContext.tokenOut"
    to: "tokenOut"
  - from: "Validators.AccountSim.ScriptContext.time"
    to: "time"
  - from: "Validators.AccountSim.newDatum"
    to: "newDatum"
  - from: "Validators.AccountSim.oldValue"
    to: "oldValue"
  - from: "Validators.AccountSim.newValue"
    to: "newValue"
  - from: "Validators.AccountSim.continuing"
    to: "continuing"
  - from: "Validators.AccountSim.getPayments"
    to: "getPayments"
  - from: "Validators.AccountSim.getPayment"
    to: "getPayments"
  - from: "Validators.AccountSim.getMintedAmount"
    to: "getMintedAmount"
  - from: "Validators.AccountSim.ownAssetClass"
    to: "ownAssetClass"
  - from: "Validators.AccountSim.checkTokenIn"
    to: "checkTokenIn"
  - from: "Validators.AccountSim.checkTokenOut"
    to: "checkTokenOut"
  - from: "Validators.AccountSim.checkSigned"
    to: "checkSigned"
  - from: "Validators.AccountSim.checkSigned"
    to: "checkSigned"
  - from: "Validators.AccountSim.iRef"
    to: "iRef"
  - from: "Validators.AccountSim.checkTokenBurned"
    to: "checkTokenBurned"
  - from: "Validators.AccountSim.consumes"
    to: "consumes"
  - from: "Validators.AccountSim.continuingAddr"
    to: "continuingAddr"
  - from: "Validators.AccountSim.checkPayment"
    to: "checkPayment"
  - from: "Validators.AccountSim.now"
    to: "now"
  - from: "Validators.AccountSim.ScriptContext.time"
    to: "time"
  - from: "Validators.AccountSim.newDatumAddr"
    to: "newDatumAddr"
  - from: "Validators.AccountSim.newValueAddr"
    to: "newValueAddr"
  - from: "Validators.AccountSim.checkTokenOutAddr"
    to: "checkTokenOutAddr"
    
  - from: "Validators.MultiSig.ScriptContext"
    to: "ScriptContext"
  - from: "Validators.MultiSig.ScriptContext.inputVal"
    to: "inputVal"
  - from: "Validators.MultiSig.ScriptContext.outputVal"
    to: "outputVal"
  - from: "Validators.MultiSig.ScriptContext.outputDatum"
    to: "outputDatum"
  - from: "Validators.MultiSig.ScriptContext.payments"
    to: "payments"
  - from: "Validators.MultiSig.ScriptContext.signature"
    to: "signature"
  - from: "Validators.MultiSig.ScriptContext.continues"
    to: "continues"
  - from: "Validators.MultiSig.ScriptContext.mint"
    to: "mint"
  - from: "Validators.MultiSig.ScriptContext.inputRef"
    to: "inputRef"
  - from: "Validators.MultiSig.ScriptContext.tokAssetClass"
    to: "tokAssetClass"
  - from: "Validators.MultiSig.ScriptContext.tokenIn"
    to: "tokenIn"
  - from: "Validators.MultiSig.ScriptContext.tokenOut"
    to: "tokenOut"
  - from: "Validators.MultiSig.ScriptContext.time"
    to: "time"
  - from: "Validators.MultiSig.newDatum"
    to: "newDatum"
  - from: "Validators.MultiSig.oldValue"
    to: "oldValue"
  - from: "Validators.MultiSig.newValue"
    to: "newValue"
  - from: "Validators.MultiSig.continuing"
    to: "continuing"
  - from: "Validators.MultiSig.getPayments"
    to: "getPayments"
  - from: "Validators.MultiSig.getPayment"
    to: "getPayments"
  - from: "Validators.MultiSig.getMintedAmount"
    to: "getMintedAmount"
  - from: "Validators.MultiSig.ownAssetClass"
    to: "ownAssetClass"
  - from: "Validators.MultiSig.checkTokenIn"
    to: "checkTokenIn"
  - from: "Validators.MultiSig.checkTokenOut"
    to: "checkTokenOut"
  - from: "Validators.MultiSig.checkSigned"
    to: "checkSigned"
  - from: "Validators.MultiSig.checkSigned"
    to: "checkSigned"
  - from: "Validators.MultiSig.iRef"
    to: "iRef"
  - from: "Validators.MultiSig.checkTokenBurned"
    to: "checkTokenBurned"
  - from: "Validators.MultiSig.consumes"
    to: "consumes"
  - from: "Validators.MultiSig.continuingAddr"
    to: "continuingAddr"
  - from: "Validators.MultiSig.checkPayment"
    to: "checkPayment"
  - from: "Validators.MultiSig.now"
    to: "now"
  - from: "Validators.MultiSig.ScriptContext.time"
    to: "time"
  - from: "Validators.MultiSig.newDatumAddr"
    to: "newDatumAddr"
  - from: "Validators.MultiSig.newValueAddr"
    to: "newValueAddr"
  - from: "Validators.MultiSig.checkTokenOutAddr"
    to: "checkTokenOutAddr"
  
  
  - from: "Validators.DEx.ScriptContext"
    to: "ScriptContext"
  - from: "Validators.DEx.ScriptContext.inputVal"
    to: "inputVal"
  - from: "Validators.DEx.ScriptContext.outputVal"
    to: "outputVal"
  - from: "Validators.DEx.ScriptContext.outputDatum"
    to: "outputDatum"
  - from: "Validators.DEx.ScriptContext.payments"
    to: "payments"
  - from: "Validators.DEx.ScriptContext.signature"
    to: "signature"
  - from: "Validators.DEx.ScriptContext.continues"
    to: "continues"
  - from: "Validators.DEx.ScriptContext.mint"
    to: "mint"
  - from: "Validators.DEx.ScriptContext.inputRef"
    to: "inputRef"
  - from: "Validators.DEx.ScriptContext.tokAssetClass"
    to: "tokAssetClass"
  - from: "Validators.DEx.ScriptContext.tokenIn"
    to: "tokenIn"
  - from: "Validators.DEx.ScriptContext.tokenOut"
    to: "tokenOut"
  - from: "Validators.DEx.ScriptContext.time"
    to: "time"
  - from: "Validators.DEx.newDatum"
    to: "newDatum"
  - from: "Validators.DEx.oldValue"
    to: "oldValue"
  - from: "Validators.DEx.newValue"
    to: "newValue"
  - from: "Validators.DEx.continuing"
    to: "continuing"
  - from: "Validators.DEx.getPayments"
    to: "getPayments"
  - from: "Validators.DEx.getPayment"
    to: "getPayments"
  - from: "Validators.DEx.getMintedAmount"
    to: "getMintedAmount"
  - from: "Validators.DEx.ownAssetClass"
    to: "ownAssetClass"
  - from: "Validators.DEx.checkTokenIn"
    to: "checkTokenIn"
  - from: "Validators.DEx.checkTokenOut"
    to: "checkTokenOut"
  - from: "Validators.DEx.checkSigned"
    to: "checkSigned"
  - from: "Validators.DEx.checkSigned"
    to: "checkSigned"
  - from: "Validators.DEx.iRef"
    to: "iRef"
  - from: "Validators.DEx.checkTokenBurned"
    to: "checkTokenBurned"
  - from: "Validators.DEx.consumes"
    to: "consumes"
  - from: "Validators.DEx.continuingAddr"
    to: "continuingAddr"
  - from: "Validators.DEx.checkPayment"
    to: "checkPayment"
  - from: "Validators.DEx.now"
    to: "now"
  - from: "Validators.DEx.ScriptContext.time"
    to: "time"
  - from: "Validators.DEx.newDatumAddr"
    to: "newDatumAddr"
  - from: "Validators.DEx.newValueAddr"
    to: "newValueAddr"
  - from: "Validators.DEx.checkTokenOutAddr"
    to: "checkTokenOutAddr"
    
   
  - from: "Validators.Template.ScriptContext"
    to: "ScriptContext"
  - from: "Validators.Template.ScriptContext.inputVal"
    to: "inputVal"
  - from: "Validators.Template.ScriptContext.outputVal"
    to: "outputVal"
  - from: "Validators.Template.ScriptContext.outputDatum"
    to: "outputDatum"
  - from: "Validators.Template.ScriptContext.payments"
    to: "payments"
  - from: "Validators.Template.ScriptContext.signature"
    to: "signature"
  - from: "Validators.Template.ScriptContext.continues"
    to: "continues"
  - from: "Validators.Template.ScriptContext.mint"
    to: "mint"
  - from: "Validators.Template.ScriptContext.inputRef"
    to: "inputRef"
  - from: "Validators.Template.ScriptContext.tokAssetClass"
    to: "tokAssetClass"
  - from: "Validators.Template.ScriptContext.tokenIn"
    to: "tokenIn"
  - from: "Validators.Template.ScriptContext.tokenOut"
    to: "tokenOut"
  - from: "Validators.Template.ScriptContext.time"
    to: "time"
  - from: "Validators.Template.newDatum"
    to: "newDatum"
  - from: "Validators.Template.oldValue"
    to: "oldValue"
  - from: "Validators.Template.newValue"
    to: "newValue"
  - from: "Validators.Template.continuing"
    to: "continuing"
  - from: "Validators.Template.getPayments"
    to: "getPayments"
  - from: "Validators.Template.getPayment"
    to: "getPayments"
  - from: "Validators.Template.getMintedAmount"
    to: "getMintedAmount"
  - from: "Validators.Template.ownAssetClass"
    to: "ownAssetClass"
  - from: "Validators.Template.checkTokenIn"
    to: "checkTokenIn"
  - from: "Validators.Template.checkTokenOut"
    to: "checkTokenOut"
  - from: "Validators.Template.checkSigned"
    to: "checkSigned"
  - from: "Validators.Template.checkSigned"
    to: "checkSigned"
  - from: "Validators.Template.iRef"
    to: "iRef"
  - from: "Validators.Template.checkTokenBurned"
    to: "checkTokenBurned"
  - from: "Validators.Template.consumes"
    to: "consumes"
  - from: "Validators.Template.continuingAddr"
    to: "continuingAddr"
  - from: "Validators.Template.checkPayment"
    to: "checkPayment"
  - from: "Validators.Template.now"
    to: "now"
  - from: "Validators.Template.ScriptContext.time"
    to: "time"
  - from: "Validators.Template.Placeholder"
    to: "Placeholder"
  - from: "Validators.Template.newDatumAddr"
    to: "newDatumAddr"
  - from: "Validators.Template.newValueAddr"
    to: "newValueAddr"
  - from: "Validators.Template.checkTokenOutAddr"
    to: "checkTokenOutAddr"
    
      