rewrites:
  - from: "MWE2.FooBar"
    to: "FOObar"
  - from: "MWE2.getFoo"
    to: "getFooo"
  - from: "MWE2.FooBar.bar1"
    to: "asdf1"
  - from: "MWE2.FooBar.bar2"
    to: "asdf2"
  - from: "MWE'.ScriptContext"
    to: "ScriptContextt"
  - from: "MWE'.getOther"
    to: "getOtherr"
  - from: "Haskell.Test.ScriptContext"
    to: "ScriptContext"
    importing: "Something"
  - from: "Haskell.Test.Foo"
    to: "Foo2"
    importing: "Something"
  - from: "Haskell.Test.ScriptContext Integer"
    to: "ScriptContext"
    importing: "Something"
  - from: "MWE2.Bar.bar1"
    to: "asdf"
    importing : "Fdsa"
  - from: "MWE.bar2"
    to: "bar2"
    importing : "Natural"
  - from: "Agda.Builtin.Nat._*_"
    to: "_*_"
    importing: "Prelude"
  - from: "Agda.Builtin.Int.Int.pos"
    to: "toInteger"
    importing: "Prelude"
  - from: "Data.Rational.Unnormalised.Base.ℚᵘ"
    to: "Rational"
    importing: "Data.Ratio"
  - from: "Data.Rational.Unnormalised.Base._*_"
    to: "_*_"
    importing: "Prelude"
  - from: "Data.Rational.Unnormalised.Base._/_"
    to: "_%_"
    importing: "Data.Ratio"
  - from: "Data.Rational.Unnormalised.Base.ℚᵘ.denominator-1"
    to: "denominatorMinus1"
    importing: "BaseExample"